name: rails                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-22.04                    # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v2

      - run: echo "This is a build step"

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - run: echo "This is a test step"

  bundler-audit:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4

      - run: docker run --rm :/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json

      - uses: actions/upload-artifact@v4
        with:
          name: bundler-audit
          path: bundle-audit-output.json
        if: always()                        # what is this for?

  integration:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-22.04
    needs: integration
    steps:
      - run: echo "This is a deploy step."
